### ISSUE TITLE
HTML, CSS is not defined

### ISSUE THREAD

**Issue by EvgeniiZaikin** [kagbogre/electron-custom-notifications#1]
Where must I take html and css? 

const notification = createNotification({
      content: html`
        <div class="notification">
          <h1>asdsadsad</h1>
          <p>zxczxczxc</p>
        </div>
      `,
      timeout: 3000,
    });

Not found name html.

**Comment by thepoliticallycorrect** [comment]
Hi. Yes, you're right, I need to fix the readme.
You can use /\*html\*/ and /\*css\*/ instead (or remove them completely). Using them with a vscode extension such as "es6-string-html" will highlight the syntax.
